services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map port 80 in the container to port 8080 on the host
    volumes:
      - ./src:/var/www/html # Mount the source code directory
    container_name: php-apache-container
